"""init models

Revision ID: e004bc6b6b6f
Revises: 
Create Date: 2025-11-21 13:17:12.054841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e004bc6b6b6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_bot_blocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время последнего обновления записи'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('habits',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_days', sa.Integer(), nullable=False),
    sa.Column('time_to_remind', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('max_streak', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время последнего обновления записи'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_habits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habits'))
    )
    op.create_index(op.f('ix_habits_id'), 'habits', ['id'], unique=False)
    op.create_index(op.f('ix_habits_is_active'), 'habits', ['is_active'], unique=False)
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_table('habitexecutions',
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('execution_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DONE', 'NOT_DONE', 'SKIPPED', name='habit_execution_status_enum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время последнего обновления записи'),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], name=op.f('fk_habitexecutions_habit_id_habits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habitexecutions')),
    sa.UniqueConstraint('habit_id', 'execution_date', name='uq_habit_execution_per_day')
    )
    op.create_index(op.f('ix_habitexecutions_execution_date'), 'habitexecutions', ['execution_date'], unique=False)
    op.create_index(op.f('ix_habitexecutions_habit_id'), 'habitexecutions', ['habit_id'], unique=False)
    op.create_index(op.f('ix_habitexecutions_id'), 'habitexecutions', ['id'], unique=False)
    op.create_index(op.f('ix_habitexecutions_status'), 'habitexecutions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_habitexecutions_status'), table_name='habitexecutions')
    op.drop_index(op.f('ix_habitexecutions_id'), table_name='habitexecutions')
    op.drop_index(op.f('ix_habitexecutions_habit_id'), table_name='habitexecutions')
    op.drop_index(op.f('ix_habitexecutions_execution_date'), table_name='habitexecutions')
    op.drop_table('habitexecutions')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_index(op.f('ix_habits_is_active'), table_name='habits')
    op.drop_index(op.f('ix_habits_id'), table_name='habits')
    op.drop_table('habits')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
