"""Add indexes for scheduler optimization

Revision ID: 140a41330e84
Revises: b569383503af
Create Date: 2026-01-15 09:47:31.661901

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "140a41330e84"
down_revision: Union[str, Sequence[str], None] = "b569383503af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_habits_time_active", "habits", ["time_to_remind", "is_active"], unique=False)
    op.create_index(op.f("ix_users_timezone"), "users", ["timezone"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_timezone"), table_name="users")
    op.drop_index("ix_habits_time_active", table_name="habits")
    # ### end Alembic commands ###
